# Generated by Django 3.2.20 on 2023-09-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('idalumo', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField(unique=True)),
                ('filiar', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20)),
                ('grado', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=2)),
                ('color_piel', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('unidad', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('telefono_movil', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
